print(7, type(7))
print(7.2, type(7.2))
print(3+4j, type(3+4j))
print(True, type(True))

print('abc', type('abc'))
print([1], type([1]))
print((1,), type((1,)))
print({1}, type({1,}))
print({'key' : 1}, type({'key' : 1}))